import Foundation

/// The header baia writes at the top of every file it generates into somebody
/// else's directory, and the one question asked of it afterwards.
///
/// **This is the substitute for herdr's begin and end markers**, and it is not a
/// like-for-like one. Their integration wraps its edits in `# >>> herdr …` and
/// `# <<< herdr …` so an uninstall can cut exactly what was added. That works in
/// a config format with comments; `~/.claude/settings.json` is JSON and has none.
///
/// So the marker moves to the file baia genuinely owns. The hook script carries
/// this header, and the entry in `settings.json` is recognised by pointing at
/// that script's path. See ``HookDocument`` for the other half.
public enum ManagedHeader {
    /// What this build ships. Bumped when the script changes in a way an existing
    /// install should be told about, which is not every edit: a comment fix is not
    /// a reason to tell somebody their install is stale.
    public static let currentVersion = 2 // 2: StopFailure registered, stdin read before any guard (2026-09-01)

    /// The key the version sits behind, and the only line here that is parsed.
    /// The others are for the human who opens the file.
    private static let versionKey = "# baia-integration-version:"

    /// The header, with no trailing newline, so a caller decides how it joins what
    /// follows.
    ///
    /// Every line is a comment because this is prepended to a shell script, and a
    /// line that executed would be a header that broke the file it describes.
    public static func emit(version: Int = currentVersion) -> String {
        """
        # Generated by baia. Do not edit.
        \(versionKey) \(version)
        # Custom hooks belong beside this file in settings.json, never inside it.
        """
    }

    /// The version an installed file declares, or nil for a file baia did not
    /// write.
    ///
    /// **Nil rather than zero**, and the distinction is the whole point: zero
    /// would make every hand-written hook read as a maximally outdated baia
    /// install and invite a reinstall over the top of it. A malformed version is
    /// nil for the same reason, since a damaged header is not evidence of an old
    /// one.
    ///
    /// Searched line by line rather than pinned to the top. An owner who added a
    /// line above it, or an editor that moved the shebang, has not uninstalled
    /// anything.
    public static func version(in text: String) -> Int? {
        for line in text.split(separator: "\n", omittingEmptySubsequences: false) {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            guard trimmed.hasPrefix(versionKey) else { continue }
            let value = trimmed.dropFirst(versionKey.count).trimmingCharacters(in: .whitespaces)
            return Int(value)
        }
        return nil
    }

    /// Whether an installed file is older than this build.
    ///
    /// **False for every answer but "older", including no answer at all.** A file
    /// with no header is not a stale baia install, and one declaring a higher
    /// version is an owner running an older baia after a newer one, where telling
    /// them to upgrade would be advice pointing the wrong way.
    public static func isOutdated(_ text: String, against current: Int = currentVersion) -> Bool {
        guard let installed = version(in: text) else { return false }
        return installed < current
    }
}
