import Foundation
import Testing

@testable import AgentIntegration

/// The header baia writes on a file it generates, and the one question anybody
/// asks of it later: is what is installed older than what this build ships.
@Suite struct ManagedHeaderTests {
    @Test func anEmittedHeaderParsesBackToItsVersion() {
        #expect(ManagedHeader.version(in: ManagedHeader.emit(version: 4)) == 4)
    }

    @Test func theDefaultEmitsTheCurrentVersion() {
        #expect(ManagedHeader.version(in: ManagedHeader.emit()) == ManagedHeader.currentVersion)
    }

    /// **Nil rather than zero.** A file with no header is one baia did not write,
    /// and treating that as version zero would report every hand-written hook as
    /// an outdated baia install.
    @Test func aFileWithNoHeaderHasNoVersion() {
        #expect(ManagedHeader.version(in: "#!/bin/sh\necho hello\n") == nil)
        #expect(ManagedHeader.version(in: "") == nil)
    }

    /// The header is found wherever it sits. An owner who added a line above it,
    /// or an editor that moved the shebang, has not uninstalled anything.
    @Test func theHeaderIsFoundOnAnyLine() {
        let moved = "#!/bin/sh\n# something the owner added\n"
            + ManagedHeader.emit(version: 2)
            + "\necho hello\n"
        #expect(ManagedHeader.version(in: moved) == 2)
    }

    /// A version that is not a number is not a version. Answering zero would make
    /// a corrupted header read as maximally outdated and prompt a reinstall over
    /// whatever damaged it.
    @Test func aMalformedVersionIsNoVersion() {
        #expect(ManagedHeader.version(in: "# baia-integration-version: soon\n") == nil)
        #expect(ManagedHeader.version(in: "# baia-integration-version:\n") == nil)
    }

    // MARK: Outdated

    @Test func anOlderInstallIsOutdated() {
        #expect(ManagedHeader.isOutdated(ManagedHeader.emit(version: 1), against: 2))
    }

    @Test func aCurrentInstallIsNot() {
        #expect(ManagedHeader.isOutdated(ManagedHeader.emit(version: 2), against: 2) == false)
    }

    /// **A newer install is not outdated either.** That is an owner who ran an
    /// older baia after a newer one, and telling them to upgrade a file that is
    /// ahead of this build would be advice in the wrong direction.
    @Test func aNewerInstallIsNotOutdated() {
        #expect(ManagedHeader.isOutdated(ManagedHeader.emit(version: 9), against: 2) == false)
    }

    /// A file baia did not write is not an outdated baia install. Saying nothing
    /// is the whole behaviour for an absent header.
    @Test func aFileWithNoHeaderIsNotOutdated() {
        #expect(ManagedHeader.isOutdated("#!/bin/sh\n", against: 2) == false)
    }

    // MARK: What the header says

    /// The three things the header exists to say, asserted so that dropping one
    /// while editing the text is a failure rather than a silent loss.
    @Test func theHeaderSaysItIsGeneratedAndWhereCustomHooksGo() {
        let header = ManagedHeader.emit()
        #expect(header.contains("Generated by baia"))
        #expect(header.contains("Do not edit"))
        #expect(header.contains("beside"))
    }

    /// Every line is a comment, because this is prepended to a shell script and a
    /// header line that executed would be a header that broke the file.
    @Test func everyHeaderLineIsAComment() {
        for line in ManagedHeader.emit().split(separator: "\n") {
            #expect(line.hasPrefix("#"), "header line is not a comment: \(line)")
        }
    }
}
